# Generated by Django 5.1 on 2026-04-05 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='orgs/logos/')),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='apps/thumbnails/')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Paramètres JSON : couleurs, modules actifs, layout, basemap…', verbose_name='Configuration')),
                ('center_lat', models.FloatField(default=3.848, verbose_name='Latitude initiale')),
                ('center_lon', models.FloatField(default=11.502, verbose_name='Longitude initiale')),
                ('zoom_default', models.IntegerField(default=7, verbose_name='Zoom initial')),
                ('zoom_min', models.IntegerField(default=5, verbose_name='Zoom minimum')),
                ('zoom_max', models.IntegerField(default=20, verbose_name='Zoom maximum')),
                ('module_incidents', models.BooleanField(default=True, verbose_name='Module Incidents')),
                ('module_interventions', models.BooleanField(default=True, verbose_name='Module Interventions')),
                ('module_analytics', models.BooleanField(default=True, verbose_name='Module Analytics')),
                ('module_export', models.BooleanField(default=True, verbose_name='Module Export')),
                ('module_editor', models.BooleanField(default=False, verbose_name='Module Éditeur géométrique')),
                ('is_public', models.BooleanField(default=False, verbose_name='Publique (sans login)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='sims_core.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['organisation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MapAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('geom_type', models.CharField(choices=[('point', 'Point / Marqueur'), ('line', 'Ligne'), ('polygon', 'Polygone / Zone'), ('text', 'Texte')], max_length=20)),
                ('geojson', models.JSONField(verbose_name='GeoJSON de la géométrie')),
                ('color', models.CharField(default='#00AADD', max_length=20)),
                ('is_shared', models.BooleanField(default=False, verbose_name="Partagée avec l'équipe")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='sims_core.application')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annotation cartographique',
                'verbose_name_plural': 'Annotations cartographiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('zoom', models.IntegerField()),
                ('active_layers', models.JSONField(default=list, verbose_name='IDs couches actives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='sims_core.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark carte',
                'verbose_name_plural': 'Bookmarks carte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur — Accès complet'), ('superviseur', 'Superviseur — Suivi opérations'), ('operateur', 'Opérateur — Saisie terrain'), ('lecteur', 'Lecteur — Consultation seule')], default='lecteur', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('ldap_dn', models.CharField(blank=True, help_text="Distinguished Name de l'entrée LDAP", max_length=500, verbose_name='DN LDAP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='sims_core.organisation', verbose_name='Organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='ApplicationLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom affiché')),
                ('geoserver_layer', models.CharField(max_length=200, verbose_name='Couche GeoServer (workspace:nom)')),
                ('layer_type', models.CharField(choices=[('WMS', 'WMS — Carte tuilée (lignes, polygones)'), ('WFS', 'WFS — Vecteur interactif (points)')], default='WMS', max_length=10)),
                ('visible_default', models.BooleanField(default=True, verbose_name='Visible par défaut')),
                ('opacity_default', models.FloatField(default=1.0, verbose_name='Opacité par défaut (0-1)')),
                ('layer_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='Groupe')),
                ('color', models.CharField(default='#00AADD', max_length=20, verbose_name='Couleur HEX')),
                ('line_width', models.FloatField(default=2.0, verbose_name='Épaisseur de ligne (px)')),
                ('point_radius', models.FloatField(default=6.0, verbose_name='Rayon des points (px)')),
                ('style_config', models.JSONField(blank=True, default=dict, help_text='SLD, filtres CQL, classification…', verbose_name='Style avancé (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='sims_core.application', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Couche cartographique',
                'verbose_name_plural': 'Couches cartographiques',
                'ordering': ['application', 'layer_order', 'name'],
                'unique_together': {('application', 'geoserver_layer')},
            },
        ),
    ]
