# Generated by Django 4.2.13 on 2026-04-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims_core', '0004_dashboard_dashboardwidget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='attributes',
            field=models.JSONField(default=list, help_text='Liste des noms de champs, ex: ["region", "type_poste"]', verbose_name='Attributs analysés'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='filters',
            field=models.JSONField(blank=True, default=dict, help_text='Filtres attributaires optionnels (CQL)', verbose_name='Filtres'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='geoserver_layer',
            field=models.CharField(help_text='Ex: eneo_gis_ws:cmrPosteSource', max_length=200, verbose_name='Couche GeoServer'),
        ),
    ]
