# Generated by Django 4.2.13 on 2026-05-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims_core', '0005_alter_dashboardwidget_attributes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AddField(
            model_name='organisation',
            name='module_analytics',
            field=models.BooleanField(default=False, verbose_name='Module Analytics'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='module_editor',
            field=models.BooleanField(default=False, verbose_name='Module Éditeur cartographique'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='module_export',
            field=models.BooleanField(default=False, verbose_name='Module Export'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='module_incidents',
            field=models.BooleanField(default=True, verbose_name='Module Incidents'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='module_interventions',
            field=models.BooleanField(default=True, verbose_name='Module Interventions'),
        ),
    ]
