# Generated by Django 4.2.13 on 2026-04-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eneo_reseau', '0002_fix_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incident',
            new_name='eneo_reseau_statut_d8c4b2_idx',
            old_name='incident_statut_priorite_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='eneo_reseau_date_si_dee426_idx',
            old_name='incident_date_sig_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='eneo_reseau_couche__b77328_idx',
            old_name='incident_couche_feature_idx',
        ),
        migrations.RenameIndex(
            model_name='intervention',
            new_name='eneo_reseau_statut_1ddee3_idx',
            old_name='intervention_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='intervention',
            new_name='eneo_reseau_date_pl_47f729_idx',
            old_name='intervention_date_plan_idx',
        ),
    ]
