# Generated by Django 4.2.13 on 2026-04-30 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eneo_reseau', '0003_rename_incident_statut_priorite_idx_eneo_reseau_statut_d8c4b2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, default='⚡', max_length=10, verbose_name='Icône (emoji)')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Type d'incident",
                'verbose_name_plural': "Types d'incident",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'équipe")),
                ('specialite', models.CharField(blank=True, max_length=150, verbose_name='Spécialité')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contact / Téléphone')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='eneo_reseau.typeincident', verbose_name="Type d'incident"),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='eneo_reseau.equipe', verbose_name='Équipe'),
        ),
    ]
