# Generated by Django 4.2.13 on 2026-04-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eneo_reseau', '0004_typeincident_equipe_alter_incident_type_incident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOuvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('couche_geoserver', models.CharField(blank=True, help_text='Nom complet de la couche GeoServer (ex: ws:transformateurs)', max_length=200, verbose_name='Couche GeoServer')),
                ('layer_key', models.CharField(blank=True, help_text='Identifiant interne de la couche côté application React (ex: transformateurs)', max_length=100, verbose_name='Clé de couche (layer_key)')),
                ('champ_cle', models.CharField(help_text="Nom de l'attribut WFS servant de code unique (ex: code_transfo)", max_length=100, verbose_name='Attribut-clé')),
                ('champ_nom', models.CharField(blank=True, help_text="Nom de l'attribut WFS pour le libellé de l'ouvrage (ex: nom_transfo)", max_length=100, verbose_name='Attribut nom')),
                ('icone', models.CharField(blank=True, default='🔌', max_length=10, verbose_name='Icône')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': "Type d'ouvrage",
                'verbose_name_plural': "Types d'ouvrage",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Identifiant unique de l'ouvrage (lu depuis GeoServer)", max_length=100, unique=True, verbose_name='Code ouvrage')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='Nom / Libellé')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_ouvrage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvrages', to='eneo_reseau.typeouvrage', verbose_name="Type d'ouvrage")),
            ],
            options={
                'verbose_name': 'Ouvrage',
                'verbose_name_plural': 'Ouvrages',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='ouvrage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='eneo_reseau.ouvrage', verbose_name='Ouvrage concerné'),
        ),
    ]
