# Generated by Django 4.2.13 on 2026-04-30 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eneo_reseau', '0005_typeouvrage_ouvrage_incident_ouvrage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interventions/photos/%Y/%m/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='eneo_reseau.intervention')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Photo d'intervention",
                'verbose_name_plural': "Photos d'intervention",
                'ordering': ['uploaded_at'],
            },
        ),
    ]
