# Generated by Django 4.2.13 on 2026-05-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eneo_reseau', '0007_typeouvrage_application_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeouvrage',
            name='couche_geoserver',
            field=models.CharField(blank=True, help_text='Synchronisé depuis application_layer.geoserver_layer (lecture seule si FK définie).', max_length=200, verbose_name='Couche GeoServer'),
        ),
        migrations.AlterField(
            model_name='typeouvrage',
            name='layer_key',
            field=models.CharField(blank=True, help_text='Synchronisé depuis application_layer.layer_key (lecture seule si FK définie).', max_length=100, verbose_name='Clé de couche (layer_key)'),
        ),
    ]
